# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8ns5p9yCG9h8ukSGWelShsYUHWjSwFv
"""

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time

# Configurações para rodar o Chrome em modo headless (sem abrir janela)
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--window-size=1920,1200')

driver = webdriver.Chrome(service=Service(), options=chrome_options)

# Abre a página de login de exemplo
driver.get("https://the-internet.herokuapp.com/login")

# Verifica se a página carregou corretamente
assert "Login" in driver.title
print("Página de login carregada com sucesso!")

# Preenche o campo de usuário
username = driver.find_element(By.ID, "username")
username.send_keys("tomsmith")

# Preenche o campo de senha
password = driver.find_element(By.ID, "password")
password.send_keys("SuperSecretPassword!")

# Clica no botão de login
login_button = driver.find_element(By.CSS_SELECTOR, "button.radius")
login_button.click()

time.sleep(2)  # Espera a resposta do servidor

# Verifica se o login foi bem-sucedido
message = driver.find_element(By.ID, "flash").text
assert "You logged into a secure area!" in message
print("Login realizado com sucesso!")

driver.quit()

!pip install selenium