# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8ns5p9yCG9h8ukSGWelShsYUHWjSwFv
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.climatempo.com.br/previsao-do-tempo/cidade/558/saopaulo-sp'
response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
    temperatura = soup.find('span', class_='-bold -gray-dark-2 -font-30 -line-height-40')
    descricao = soup.find('div', class_='-gray -line-height-20 -font-12 -margin-bottom-10')

    if temperatura and descricao:
        print(f'Temperatura atual em São Paulo: {temperatura.text.strip()}')
        print(f'Condição do tempo: {descricao.text.strip()}')
    else:
        print('Não foi possível encontrar os dados do tempo.')
else:
    print(f'Falha ao acessar a página. Código de status: {response.status_code}')