# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb
"""

import requests

def test_api_usuarios():
    url = "https://jsonplaceholder.typicode.com/users/1"
    response = requests.get(url)

    # Verifica se o status da resposta é 200 (OK)
    assert response.status_code == 200, f"Erro: Status code {response.status_code}"

    data = response.json()

    # Verifica se a chave 'email' está presente no JSON retornado
    assert "email" in data, "Erro: A chave 'email' não está presente nos dados JSON"

    print("Teste da API para usuários realizado com sucesso!")

test_api_usuarios()