# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8ns5p9yCG9h8ukSGWelShsYUHWjSwFv
"""

import unittest

# Função que será testada
def somar(a, b):
    return a + b

# Classe de teste que herda de unittest.TestCase
class TestSomar(unittest.TestCase):
    def test_somar_positivos(self):
        self.assertEqual(somar(3, 7), 10)

    def test_somar_negativos(self):
        self.assertEqual(somar(-1, -5), -6)

    def test_somar_com_zero(self):
        self.assertEqual(somar(0, 5), 5)

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)